"""empty message

Revision ID: f3b0b0ba59ed
Revises: 
Create Date: 2026-10-08 20:02:54.193119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b0b0ba59ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuditEvent',
    sa.Column('idAuditEvent', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('idAuditEvent')
    )
    with op.batch_alter_table('AuditEvent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AuditEvent_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('Categoria',
    sa.Column('idCategoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idCategoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Roles',
    sa.Column('idRol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('idRol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Prenda',
    sa.Column('idPrenda', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('nombre_prenda', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('precio_alquiler', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['Categoria.idCategoria'], ),
    sa.PrimaryKeyConstraint('idPrenda')
    )
    op.create_table('Usuarios',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idRol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('Contrasena', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idRol'], ['Roles.idRol'], ),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('Lote',
    sa.Column('idLote', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idPrenda', sa.Integer(), nullable=False),
    sa.Column('nombre_lote', sa.String(length=100), nullable=False),
    sa.Column('descripcion_lote', sa.Text(), nullable=True),
    sa.Column('cantidad_prendas', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idPrenda'], ['Prenda.idPrenda'], ),
    sa.PrimaryKeyConstraint('idLote')
    )
    op.create_table('PrendaImagen',
    sa.Column('idImagen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idPrenda', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idPrenda'], ['Prenda.idPrenda'], ),
    sa.PrimaryKeyConstraint('idImagen')
    )
    op.create_table('Reserva',
    sa.Column('idReserva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_administrador', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.Date(), nullable=False),
    sa.Column('fecha_evento', sa.Date(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('Pendiente', 'Confirmada', 'Entregada', 'Finalizada', 'Cancelada'), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['Usuarios.idUsuario'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['Usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idReserva')
    )
    op.create_table('Cita',
    sa.Column('idCita', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_administrador', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=True),
    sa.Column('fecha_cita', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.Enum('Pendiente', 'Atendida', 'Cancelada'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['Usuarios.idUsuario'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['Usuarios.idUsuario'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['Reserva.idReserva'], ),
    sa.PrimaryKeyConstraint('idCita')
    )
    op.create_table('Comprobante',
    sa.Column('idComprobante', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idReserva', sa.Integer(), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=30), nullable=False),
    sa.Column('tipo_comprobante', sa.Enum('Ticket', 'Factura', 'Recibo'), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('Pendiente', 'Emitido', 'Anulado'), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idReserva'], ['Reserva.idReserva'], ),
    sa.PrimaryKeyConstraint('idComprobante'),
    sa.UniqueConstraint('numero_comprobante')
    )
    op.create_table('Inventario',
    sa.Column('idInventario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idPrenda', sa.Integer(), nullable=False),
    sa.Column('idLote', sa.Integer(), nullable=True),
    sa.Column('codigo_interno', sa.String(length=30), nullable=False),
    sa.Column('talla', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.Enum('Disponible', 'Reservado', 'Alquilado', 'Reparacion'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idLote'], ['Lote.idLote'], ),
    sa.ForeignKeyConstraint(['idPrenda'], ['Prenda.idPrenda'], ),
    sa.PrimaryKeyConstraint('idInventario'),
    sa.UniqueConstraint('codigo_interno')
    )
    op.create_table('Detalle_Reserva',
    sa.Column('idDetalle_Reserva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idReserva', sa.Integer(), nullable=False),
    sa.Column('idInventario', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['idInventario'], ['Inventario.idInventario'], ),
    sa.ForeignKeyConstraint(['idReserva'], ['Reserva.idReserva'], ),
    sa.PrimaryKeyConstraint('idDetalle_Reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Detalle_Reserva')
    op.drop_table('Inventario')
    op.drop_table('Comprobante')
    op.drop_table('Cita')
    op.drop_table('Reserva')
    op.drop_table('PrendaImagen')
    op.drop_table('Lote')
    op.drop_table('Usuarios')
    op.drop_table('Prenda')
    op.drop_table('Roles')
    op.drop_table('Categoria')
    with op.batch_alter_table('AuditEvent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AuditEvent_occurred_at'))

    op.drop_table('AuditEvent')
    # ### end Alembic commands ###
